import assert from "node:assert/strict"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import test from "node:test"

import { Database } from "../js/database.js"
import { createHost } from "./host.js"

test("database executes persistent relational SQL", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-database-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, name TEXT NOT NULL, score INT)")
  database.execute("INSERT INTO users VALUES (1, 'Ada', 9), (2, 'Linus', 7), (3, 'Grace', 10)")
  assert.deepEqual(database.execute("SELECT name FROM users WHERE score >= 9 ORDER BY name"), [["Ada"], ["Grace"]])
  assert.deepEqual(database.execute("SELECT COUNT(*), MAX(score) FROM users"), [[3n, 10]])
  database.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT name FROM users WHERE id = 2"), [["Linus"]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("updates deletes and rollbacks preserve row versions", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-mvcc-"))
  const file = path.join(directory, "data.db")
  const database = Database.open(file, createHost())
  database.execute("CREATE TABLE accounts (id BIGINT PRIMARY KEY, balance INT NOT NULL)")
  database.execute("INSERT INTO accounts VALUES (1, 100), (2, 200)")
  database.execute("BEGIN")
  database.execute("UPDATE accounts SET balance = balance + 50 WHERE id = 1")
  database.execute("DELETE FROM accounts WHERE id = 2")
  database.execute("ROLLBACK")
  assert.deepEqual(database.execute("SELECT id, balance FROM accounts ORDER BY id"), [[1n, 100], [2n, 200]])
  database.execute("UPDATE accounts SET balance = 125 WHERE id = 1")
  database.execute("DELETE FROM accounts WHERE id = 2")
  assert.deepEqual(database.execute("SELECT id, balance FROM accounts"), [[1n, 125]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("vacuum reclaims dead tuples after active snapshots release them", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-vacuum-"))
  const file = path.join(directory, "data.db")
  let database = Database.open(file, createHost())
  database.execute("CREATE TABLE records (id BIGINT PRIMARY KEY, value TEXT NOT NULL)")
  database.execute("INSERT INTO records VALUES (1, 'old'), (2, 'live')")
  const reader = database.createSession()
  database.execute("BEGIN READ ONLY", reader)
  assert.throws(() => database.execute("VACUUM records", reader), /read-only transaction/)
  database.execute("DELETE FROM records WHERE id = 1")
  assert.deepEqual(database.execute("SELECT * FROM records ORDER BY id", reader), [[1n, "old"], [2n, "live"]])
  assert.deepEqual(database.execute("VACUUM records"), { status: "VACUUM", rows: 0 })
  database.execute("COMMIT", reader)
  assert.deepEqual(database.execute("VACUUM records"), { status: "VACUUM", rows: 1 })
  database.execute("INSERT INTO records VALUES (3, 'reused')")
  database.close()
  database = Database.open(file, createHost())
  assert.deepEqual(database.execute("SELECT * FROM records ORDER BY id"), [[2n, "live"], [3n, "reused"]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("transactions larger than the buffer pool commit without stealing pages", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-large-transaction-"))
  const file = path.join(directory, "data.db")
  let database = Database.open(file, createHost())
  database.execute("CREATE TABLE payloads (id BIGINT PRIMARY KEY, value TEXT NOT NULL)")
  const insert = database.prepare("INSERT INTO payloads VALUES (?, ?)")
  database.execute("BEGIN")
  for (let id = 1; id <= 130; id += 1) {
    insert.execute([BigInt(id), "x".repeat(7000)])
  }
  database.execute("COMMIT")
  database.close()
  database = Database.open(file, createHost())
  assert.deepEqual(database.execute("SELECT COUNT(*) FROM payloads"), [[130n]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("primary unique not null and foreign keys reject invalid rows", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-constraints-"))
  const database = Database.open(path.join(directory, "data.db"), createHost())
  database.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, email TEXT UNIQUE NOT NULL)")
  database.execute("CREATE TABLE orders (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES users(id))")
  database.execute("INSERT INTO users VALUES (1, 'ada@example.test')")
  assert.throws(() => database.execute("INSERT INTO users VALUES (2, 'ada@example.test')"), /Unique constraint/)
  assert.throws(() => database.execute("INSERT INTO users VALUES (3, NULL)"), /cannot be null/)
  assert.throws(() => database.execute("INSERT INTO orders VALUES (1, 99)"), /Foreign key/)
  database.execute("INSERT INTO orders VALUES (1, 1)")
  assert.throws(() => database.execute("DELETE FROM users WHERE id = 1"), /Delete restricted/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("joins limits aggregates and explain use the query pipeline", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-query-"))
  const database = Database.open(path.join(directory, "data.db"), createHost())
  database.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, name TEXT NOT NULL)")
  database.execute("CREATE TABLE orders (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, amount INT NOT NULL)")
  database.execute("INSERT INTO users VALUES (1, 'Ada'), (2, 'Grace')")
  database.execute("INSERT INTO orders VALUES (1, 1, 20), (2, 1, 30), (3, 2, 40)")
  assert.deepEqual(database.execute("SELECT u.name, o.amount FROM users AS u INNER JOIN orders AS o ON o.user_id = u.id ORDER BY o.amount DESC LIMIT 2"), [["Grace", 40], ["Ada", 30]])
  assert.match(database.execute("EXPLAIN SELECT name FROM users WHERE id = 1"), /IndexScan/)
  assert.match(database.execute("EXPLAIN ANALYZE SELECT name FROM users WHERE id = 1"), /rows: 1, time: [0-9.]+ ms/)
  const prepared = database.prepare("SELECT name FROM users WHERE id = ?")
  assert.deepEqual(prepared.execute([1n]), [["Ada"]])
  const preparedUpdate = database.prepare("UPDATE users SET name = ? WHERE id = ?")
  assert.deepEqual(preparedUpdate.execute(["Augusta", 1n]), { status: "UPDATE", rows: 1 })
  assert.deepEqual(prepared.execute([1n]), [["Augusta"]])
  assert.throws(() => prepared.execute([]), /Expected 1 parameters/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("rolled back DDL stays absent after restart", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-ddl-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("BEGIN")
  database.execute("CREATE TABLE temporary_table (id BIGINT PRIMARY KEY)")
  database.execute("ROLLBACK")
  database.close()
  database = Database.open(file, host)
  assert.throws(() => database.execute("SELECT * FROM temporary_table"), /does not exist/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("rollback invalidates plans compiled against transactional DDL", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-plan-rollback-"))
  const file = path.join(directory, "data.db")
  const database = Database.open(file, createHost())
  database.execute("CREATE TABLE plan_table (id BIGINT PRIMARY KEY)")
  database.execute("BEGIN")
  database.execute("DROP TABLE plan_table")
  database.execute("CREATE TABLE plan_table (id BIGINT PRIMARY KEY, temporary_value TEXT)")
  database.execute("SELECT temporary_value FROM plan_table")
  database.execute("ROLLBACK")
  assert.throws(() => database.execute("SELECT temporary_value FROM plan_table"), /Unknown column/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("secondary indexes rebuild from persisted heap rows", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-index-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("CREATE TABLE people (id BIGINT PRIMARY KEY, email TEXT NOT NULL)")
  database.execute("CREATE UNIQUE INDEX people_email ON people(email)")
  database.execute("INSERT INTO people VALUES (1, 'one@test'), (2, 'two@test')")
  database.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT id FROM people WHERE email = 'two@test'"), [[2n]])
  assert.match(database.execute("EXPLAIN SELECT id FROM people WHERE email = 'two@test'"), /people_email/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("database metrics expose storage transaction and query work", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-stats-"))
  const database = Database.open(path.join(directory, "data.db"), createHost())
  database.execute("CREATE TABLE metric_values (id BIGINT PRIMARY KEY)")
  database.execute("INSERT INTO metric_values VALUES (1)")
  database.execute("SELECT * FROM metric_values")
  const stats = database.stats()
  assert.equal(stats.transactionsCommitted, 3)
  assert.equal(stats.queriesExecuted, 3)
  assert.ok(stats.pagesWritten > 0)
  assert.ok(stats.walFsyncs > 0)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("autocommit reads do not write WAL or retain transactions", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-read-only-"))
  const file = path.join(directory, "data.db")
  const database = Database.open(file, createHost())
  database.execute("CREATE TABLE values_table (id BIGINT PRIMARY KEY)")
  database.execute("INSERT INTO values_table VALUES (1)")
  const before = fs.statSync(`${file}.wal`).size
  assert.deepEqual(database.execute("SELECT * FROM values_table WHERE id = 1"), [[1n]])
  assert.equal(fs.statSync(`${file}.wal`).size, before)
  assert.equal(database.transactions.transactions.size, 0)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("catalog survives an abrupt close after table creation", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-catalog-crash-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  const database = Database.open(file, host)
  database.execute("CREATE TABLE durable_catalog (id BIGINT PRIMARY KEY)")
  database.wal.close()
  database.pager.close()
  const reopened = Database.open(file, host)
  assert.deepEqual(reopened.execute("SELECT * FROM durable_catalog"), [])
  reopened.close()
  fs.rmSync(directory, { recursive: true })
})

test("recovery replays committed pages after a crash before data flush", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-redo-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let crash = false
  host.debug.crashPoint = (point) => {
    if (crash && point === "after-commit-before-page-flush") {
      throw new Error("simulated crash")
    }
  }
  const database = Database.open(file, host)
  database.execute("CREATE TABLE recovered_rows (id BIGINT PRIMARY KEY, value TEXT NOT NULL)")
  crash = true
  assert.throws(() => database.execute("INSERT INTO recovered_rows VALUES (1, 'durable')"), /simulated crash/)
  database.wal.close()
  database.pager.close()
  crash = false
  const reopened = Database.open(file, host)
  assert.deepEqual(reopened.execute("SELECT * FROM recovered_rows"), [[1n, "durable"]])
  reopened.close()
  fs.rmSync(directory, { recursive: true })
})

test("uncommitted DDL stays invisible after an abrupt close", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-ddl-crash-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  const database = Database.open(file, host)
  database.execute("BEGIN")
  database.execute("CREATE TABLE never_committed (id BIGINT PRIMARY KEY)")
  database.wal.close()
  database.pager.close()
  const reopened = Database.open(file, host)
  assert.throws(() => reopened.execute("SELECT * FROM never_committed"), /does not exist/)
  reopened.close()
  fs.rmSync(directory, { recursive: true })
})

test("catalog spans multiple pages", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-large-catalog-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("BEGIN")
  for (let index = 0; index < 250; index += 1) {
    database.execute(`CREATE TABLE catalog_table_${index} (id BIGINT PRIMARY KEY, value_${index} TEXT NOT NULL)`)
  }
  database.execute("COMMIT")
  database.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT * FROM catalog_table_249"), [])
  assert.ok(database.catalog.pageIds.length > 1)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("indexes exclude inserts from transactions interrupted by a crash", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-index-insert-crash-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("CREATE TABLE indexed_rows (id BIGINT PRIMARY KEY)")
  database.execute("BEGIN")
  database.execute("INSERT INTO indexed_rows VALUES (1)")
  database.bufferPool.flushAll()
  database.wal.close()
  database.pager.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT * FROM indexed_rows WHERE id = 1"), [])
  database.execute("INSERT INTO indexed_rows VALUES (1)")
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("indexes retain deletes from transactions interrupted by a crash", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-index-delete-crash-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("CREATE TABLE indexed_rows (id BIGINT PRIMARY KEY)")
  database.execute("INSERT INTO indexed_rows VALUES (1)")
  database.execute("BEGIN")
  database.execute("DELETE FROM indexed_rows WHERE id = 1")
  database.bufferPool.flushAll()
  database.wal.close()
  database.pager.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT * FROM indexed_rows WHERE id = 1"), [[1n]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})
